#!/usr/bin/env python3
"""Build tokens.css and tailwind.css from tokens.json and tokens.dark.json.

Standard library only. The JSON files are the source of truth. This script
writes the two CSS files, so the CSS never drifts from the tokens.

    python3 replica/design/build_tokens.py           # write tokens.css and tailwind.css
    python3 replica/design/build_tokens.py --check   # exit 1 if either file is out of date

Before it writes anything, it checks that:
- both JSON files have the same keys at every level;
- only "color", "shadow", "_about" and "_theme" differ between them;
- both files have the same "pairs" list, and every pair names a real colour;
- every colour is a hex value, or an rgb()/rgba() value for the overlay.

It does not check contrast. Run contrast.py on both files for that:

    python3 .claude/skills/replica-design/contrast.py replica/design/tokens.json
    python3 .claude/skills/replica-design/contrast.py replica/design/tokens.dark.json
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
THEMED = {"color", "shadow", "_about", "_theme"}
HEX = re.compile(r"^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")
RGB = re.compile(r"^rgba?\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*(,\s*(0|1|0?\.\d+)\s*)?\)$")

# Role name -> Tailwind colour name, where the plain role name would read badly
# as a utility (text-text, border-border-input). Every other role keeps its name.
TW_COLOR_RENAME = {
    "text": "fg",               # text-fg
    "text-muted": "muted",      # text-muted
    "border-strong": "strong",  # border-strong
    "border-input": "input",    # border-input
}
# Layout keys that are maximum widths become Tailwind containers (max-w-*, w-*).
CONTAINER_KEY = re.compile(r"(-max$|^dialog-|^drawer-)")

HEADER = (
    "Generated by build_tokens.py from tokens.json (light) and tokens.dark.json (dark).\n"
    "   Do not edit by hand. Change the JSON, run contrast.py on both files, then run\n"
    "   python3 replica/design/build_tokens.py."
)


class TokenError(Exception):
    pass


# -- reading and checking ----------------------------------------------------

def load(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError) as exc:
        raise TokenError("%s: %s" % (path, exc))


def key_diff(a, b, path=""):
    """Paths where the two documents do not have the same keys."""
    out = []
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            p = "%s.%s" % (path, k) if path else k
            if k not in a:
                out.append("%s missing in light" % p)
            elif k not in b:
                out.append("%s missing in dark" % p)
            else:
                out.extend(key_diff(a[k], b[k], p))
    elif isinstance(a, dict) != isinstance(b, dict):
        out.append("%s is an object in one file only" % path)
    return out


def check(light, dark):
    problems = key_diff(light, dark)
    for k in sorted(set(light) - THEMED):
        if k in dark and light[k] != dark[k]:
            problems.append("%s differs between the files; only %s may differ" % (k, ", ".join(sorted(THEMED))))
    for name, doc in (("light", light), ("dark", dark)):
        for role, value in doc.get("color", {}).items():
            if not isinstance(value, str) or not (HEX.match(value) or RGB.match(value)):
                problems.append("%s color.%s is not a hex or rgb() value: %r" % (name, role, value))
        for pair in doc.get("pairs", []):
            for role in pair[:2]:
                if role not in doc.get("color", {}):
                    problems.append("%s pair %s names an unknown colour %r" % (name, pair, role))
    if problems:
        raise TokenError("token files disagree:\n  " + "\n  ".join(problems))


# -- helpers -------------------------------------------------------------------

def rem(px):
    if px == 0:
        return "0px"
    return "%srem" % ("%.4f" % (px / 16.0)).rstrip("0").rstrip(".")


def public(d):
    """Items whose key does not start with an underscore (notes)."""
    return [(k, v) for k, v in d.items() if not k.startswith("_")]


def space_name(px):
    step = px / 4.0
    return ("%g" % step).replace(".", "_")


def font_stack(stack, font_vars):
    """Wrap each self-hosted family as var(--font-x, Family) for next/font."""
    out = []
    for item in (s.strip() for s in stack.split(",")):
        family = item.strip('"').strip("'")
        var = font_vars.get(family)
        out.append("var(%s, %s)" % (var, item) if var else item)
    return ", ".join(out)


def block(selector, lines, indent=""):
    body = "\n".join(indent + "  " + ln if ln else "" for ln in lines)
    return "%s%s {\n%s\n%s}" % (indent, selector, body, indent)


def colour_lines(doc):
    lines = ["/* colour roles */"]
    lines += ["--%s: %s;" % (k, v) for k, v in doc["color"].items()]
    lines += ["", "/* elevation (box-shadow) */"]
    lines += ["--elevation-%s: %s;" % (k, v) for k, v in public(doc["shadow"])]
    return lines


def shared_lines(t):
    L = []
    L.append("/* font families. Staff app: sans. Public pages: public (system fonts only). */")
    for k, v in public(t["font"]):
        L.append("--family-%s: %s;" % (k, font_stack(v, dict(public(t.get("font-var", {}))))))
    L += ["", "/* font weights */"]
    L += ["--weight-%s: %s;" % (k, v) for k, v in public(t["weight"])]
    L += ["", "/* type scale: size, line height, default weight */"]
    for k, v in public(t["type"]):
        L.append("--type-%s-size: %s;" % (k, rem(v["size"])))
        L.append("--type-%s-line: %s;" % (k, rem(v["line"])))
        L.append("--type-%s-weight: %s;" % (k, v["weight"]))
    L += ["", "/* line heights as ratios (prose = multi-line user text) */"]
    L += ["--line-%s: %s;" % (k, v) for k, v in public(t["leading"])]
    L += ["", "/* spacing, 4 px base. --space-N = N x 4 px, the same steps as Tailwind's p-N. */"]
    L += ["--space-%s: %s;" % (space_name(px), rem(px)) for px in t["space"]]
    L += ["", "/* radius */"]
    L += ["--rounded-%s: %spx;" % (k, v) for k, v in public(t["radius"])]
    L += ["", "/* motion */"]
    for k, v in public(t["motion"]):
        if k == "ease":
            L.append("--easing-standard: %s;" % v)
        elif k.startswith("ease-"):
            L.append("--easing-%s: %s;" % (k[5:], v))
        else:
            L.append("--motion-%s: %s;" % (k, v))
    L += ["", "/* focus outline */"]
    L += ["--focus-%s: %spx;" % (k, v) for k, v in public(t["focus"])]
    L += ["", "/* layout */"]
    L += ["--layout-%s: %s;" % (k, rem(v)) for k, v in public(t["layout"])]
    L += ["", "/* breakpoints, for matchMedia in JS. CSS media queries cannot read custom properties. */"]
    L += ["--bp-%s: %s;" % (k, rem(v)) for k, v in public(t["breakpoint"])]
    L += ["", "/* control, row and hit-area sizes */"]
    L += ["--size-%s: %s;" % (k, rem(v)) for k, v in public(t["size"])]
    L += ["", "/* icons (lucide-react). stroke is Lucide's default, scaled with the icon. */"]
    L += ["--icon-%s: %s;" % (k, v if k == "stroke" else rem(v)) for k, v in public(t["icon"])]
    L += ["", "/* stacking order */"]
    L += ["--z-%s: %s;" % (k, v) for k, v in public(t["z"])]
    return L


# -- tokens.css ----------------------------------------------------------------

def tokens_css(light, dark):
    motion_keys = [k for k, _ in public(light["motion"]) if not k.startswith("ease")]
    stop = [
        "animation-duration: 0.01ms !important;",
        "animation-delay: 0ms !important;",
        "animation-iteration-count: 1 !important;",
        "transition-duration: 0.01ms !important;",
        "transition-delay: 0ms !important;",
        "scroll-behavior: auto !important;",
    ]
    zero = ["--motion-%s: 0.01ms;" % k for k in motion_keys]
    dark_lines = ["color-scheme: dark;", ""] + colour_lines(dark)
    parts = [
        "/* tokens.css\n   " + HEADER + "\n\n"
        "   Light values and every theme-independent token sit on :root. Dark values\n"
        "   appear twice: for people who chose System while their OS is dark, and for\n"
        "   people who chose Dark. Public pages render <html data-theme=\"light\"> and\n"
        "   stay light. */",
        "",
        block(":root", ["color-scheme: light;", ""] + colour_lines(light) + [""] + shared_lines(light)),
        "",
        "/* Dark theme: the person chose System and the OS is dark. */",
        "@media (prefers-color-scheme: dark) {\n"
        + block(':root:not([data-theme="light"])', dark_lines, "  ") + "\n}",
        "",
        "/* Dark theme: the person chose Dark. */",
        block(':root[data-theme="dark"]', dark_lines),
        "",
        "/* Reduced motion: the OS setting, or the in-app setting, which puts\n"
        "   data-motion=\"reduce\" on <html>. All movement stops. Durations collapse to\n"
        "   0.01ms rather than 0 so animationend and transitionend still fire (Radix\n"
        "   waits for them before it unmounts a closed dialog). Spinners stop after one\n"
        "   frame; components show the text \"Loading\" next to them. */",
        "@media (prefers-reduced-motion: reduce) {\n"
        + block(":root", zero, "  ") + "\n"
        + block("*,\n  *::before,\n  *::after", stop, "  ") + "\n}",
        "",
        block(':root[data-motion="reduce"]', zero),
        "",
        block(':root[data-motion="reduce"],\n:root[data-motion="reduce"] *,\n'
              ':root[data-motion="reduce"] *::before,\n:root[data-motion="reduce"] *::after', stop),
        "",
    ]
    return "\n".join(parts)


# -- tailwind.css --------------------------------------------------------------

def tw_color(role):
    return TW_COLOR_RENAME.get(role, role)


def tailwind_css(t):
    colors = list(t["color"])
    layout = public(t["layout"])
    containers = [(k, v) for k, v in layout if CONTAINER_KEY.search(k)]
    spacing = [(k, v) for k, v in layout if not CONTAINER_KEY.search(k)]
    sizes = public(t["size"])
    icons = [(k, v) for k, v in public(t["icon"]) if k != "stroke"]
    motion = [(k, v) for k, v in public(t["motion"]) if not k.startswith("ease")]

    def cname(k):
        return re.sub(r"-max$", "", k)

    def names(prefix, items):
        return " ".join(prefix + x for x in items)

    surfaces = [c for c in colors if c in ("bg", "chart-surface") or c.startswith("surface")]
    tones = [c for c in ("danger", "success", "warning", "info") if c in t["color"]]
    charts = [c for c in colors if c.startswith("chart-") and c != "chart-surface"]
    doc = [
        "/* tailwind.css",
        "   " + HEADER,
        "",
        "   Tailwind CSS v4 mapping. @theme inline points each utility at a custom",
        "   property from tokens.css, so a theme switch changes values, not classes.",
        "   Components never write raw hex and never use dark: for colour. Tailwind's",
        "   default palette, type sizes, radii, shadows and easings are switched off",
        "   below, so bg-blue-500 or text-2xl do not exist.",
        "",
        "   Utility names",
        "   - Fills:    " + names("bg-", surfaces),
        "               bg-accent bg-accent-hover bg-accent-subtle bg-inverse bg-overlay",
        "               " + " ".join("bg-%s bg-%s-subtle" % (x, x) for x in tones),
        "   - Text:     text-fg text-muted text-accent text-on-accent text-on-inverse",
        "               " + " ".join("text-%s text-on-%s" % (x, x) for x in tones),
        "   - Borders:  border (defaults to the border role) border-border border-strong border-input",
        "               border-accent border-danger (invalid field)",
        "   - Focus:    automatic on :focus-visible (outline, focus-ring colour, 2px, offset 2px).",
        "               Add focus-inset inside rows, menu items and listbox options.",
        "   - Charts:   " + names("fill-", charts[:2]) + " ... (also stroke-, bg-, text-)",
        "   - Type:     " + names("text-", [k for k, _ in public(t["type"])]),
        "               (each sets size, line height and a default weight)",
        "               " + names("leading-", [k for k, _ in public(t["leading"])]),
        "               " + names("font-", [k for k, _ in public(t["weight"])]),
        "               font-sans (staff app) font-public (public pages) font-mono",
        "   - Radius:   " + names("rounded-", [k for k, _ in public(t["radius"])]),
        "   - Shadow:   " + names("shadow-", [k for k, _ in public(t["shadow"])]),
        "   - Motion:   " + names("duration-", [k for k, _ in motion]) + " ease-standard ease-exit",
        "               motion-safe: and motion-reduce: follow the OS setting and data-motion=\"reduce\".",
        "   - Sizes:    h-control-xs h-control-sm h-control-md h-control-lg",
        "               h-row h-row-compact h-row-header h-table-footer h-menu-item h-chip h-kv-row",
        "               size-checkbox min-h-hit min-w-hit min-h-hit-public min-w-hit-public",
        "               size-avatar-sm size-avatar-md size-avatar-lg size-icon-sm size-icon-md size-icon-lg",
        "   - Layout:   w-sidebar w-sidebar-collapsed h-header h-pagebar w-subnav w-kv-label",
        "               px-gutter px-gutter-sm gap-section-gap",
        "               " + names("max-w-", [cname(k) for k, _ in containers]),
        "   - Spacing:  Tailwind's own 4 px scale: p-1 = 4px, p-4 = 16px, p-5 = 20px.",
        "   - Stacking: z-(--z-sticky) z-(--z-header) z-(--z-modal) z-(--z-popover) z-(--z-toast) ...",
        "   - Screens:  " + " ".join("%s: %dpx" % (k, v) for k, v in public(t["breakpoint"])),
        "",
        "   Theme and surface switches on <html>:",
        "   - data-theme=\"light\" | \"dark\", or no attribute to follow the OS (System).",
        "   - data-surface=\"public\" on public pages (enquiry form, checkout, consent):",
        "     system fonts, 16 px body and inputs. Public pages also set data-theme=\"light\".",
        "   - data-motion=\"reduce\" when the person turned on Reduce motion.",
        "*/",
        "",
        '@import "tailwindcss";',
        '@import "./tokens.css";',
        "",
        "/* Switch off Tailwind's defaults so only our tokens exist. */",
        "@theme {",
        "  --color-*: initial;",
        "  --text-*: initial;",
        "  --leading-*: initial;",
        "  --font-*: initial;",
        "  --font-weight-*: initial;",
        "  --radius-*: initial;",
        "  --shadow-*: initial;",
        "  --inset-shadow-*: initial;",
        "  --drop-shadow-*: initial;",
        "  --ease-*: initial;",
        "  --breakpoint-*: initial;",
        "",
        "  /* Breakpoints must be literal values: media queries cannot read var(). */",
    ]
    doc += ["  --breakpoint-%s: %s;" % (k, rem(v)) for k, v in public(t["breakpoint"])]
    doc += ["}", "", "@theme inline {", "  /* colours */"]
    doc += ["  --color-%s: var(--%s);" % (tw_color(c), c) for c in colors]
    doc += ["", "  /* fonts */"]
    doc += ["  --font-%s: var(--family-%s);" % (k, k) for k, _ in public(t["font"])]
    doc += ["  --font-weight-%s: var(--weight-%s);" % (k, k) for k, _ in public(t["weight"])]
    doc += ["", "  /* type scale */"]
    for k, _ in public(t["type"]):
        doc.append("  --text-%s: var(--type-%s-size);" % (k, k))
        doc.append("  --text-%s--line-height: var(--type-%s-line);" % (k, k))
        doc.append("  --text-%s--font-weight: var(--type-%s-weight);" % (k, k))
    doc += ["  --leading-%s: var(--line-%s);" % (k, k) for k, _ in public(t["leading"])]
    doc += ["", "  /* radius and shadow */"]
    doc += ["  --radius-%s: var(--rounded-%s);" % (k, k) for k, _ in public(t["radius"])]
    doc += ["  --shadow-%s: var(--elevation-%s);" % (k, k) for k, _ in public(t["shadow"])]
    doc += ["", "  /* motion */",
            "  --ease-standard: var(--easing-standard);",
            "  --ease-exit: var(--easing-exit);",
            "  --default-transition-duration: var(--motion-base);",
            "  --default-transition-timing-function: var(--easing-standard);",
            "", "  /* named sizes (h-*, w-*, size-*, min-h-*, p-*, gap-*) */"]
    doc += ["  --spacing-%s: var(--layout-%s);" % (k, k) for k, _ in spacing]
    doc += ["  --spacing-%s: var(--size-%s);" % (k, k) for k, _ in sizes]
    doc += ["  --spacing-icon-%s: var(--icon-%s);" % (k, k) for k, _ in icons]
    doc += ["", "  /* maximum widths (max-w-*, w-*) */"]
    doc += ["  --container-%s: var(--layout-%s);" % (cname(k), k) for k, _ in containers]
    doc += ["}", ""]
    doc += [
        "/* dark: is rarely needed (components use role utilities). When it is, it",
        "   follows the same two switches as tokens.css. */",
        "@custom-variant dark {",
        "  @media (prefers-color-scheme: dark) {",
        '    &:where(:root:not([data-theme="light"]), :root:not([data-theme="light"]) *) {',
        "      @slot;",
        "    }",
        "  }",
        '  &:where([data-theme="dark"], [data-theme="dark"] *) {',
        "    @slot;",
        "  }",
        "}",
        "",
        "/* Reduced motion. Tailwind's motion-safe: and motion-reduce: read only the OS",
        "   setting; these versions also read the in-app setting (data-motion=\"reduce\").",
        "   The rule that stops all movement lives in tokens.css. */",
        "@custom-variant motion-safe {",
        "  @media (prefers-reduced-motion: no-preference) {",
        '    &:where(:root:not([data-motion="reduce"]), :root:not([data-motion="reduce"]) *) {',
        "      @slot;",
        "    }",
        "  }",
        "}",
        "@custom-variant motion-reduce {",
        "  @media (prefers-reduced-motion: reduce) {",
        "    @slot;",
        "  }",
        '  &:where([data-motion="reduce"], [data-motion="reduce"] *) {',
        "    @slot;",
        "  }",
        "}",
        "",
    ]
    for k, _ in motion:
        doc += ["@utility duration-%s {" % k,
                "  --tw-duration: var(--motion-%s);" % k,
                "  transition-duration: var(--motion-%s);" % k,
                "}"]
    doc += [
        "",
        "/* Focus inside rows, menu items and listbox options, where an outer ring",
        "   would be clipped. */",
        "@utility focus-inset {",
        "  outline-offset: var(--focus-inset);",
        "}",
        "",
        "@layer base {",
        "  *,",
        "  ::before,",
        "  ::after,",
        "  ::backdrop,",
        "  ::file-selector-button {",
        "    border-color: var(--border);",
        "  }",
        "",
        "  html {",
        "    font-family: var(--family-sans);",
        "    background-color: var(--bg);",
        "    color: var(--text);",
        "  }",
        "",
        "  /* Staff screens: 14 px body. */",
        "  body {",
        "    font-size: var(--type-sm-size);",
        "    line-height: var(--type-sm-line);",
        "  }",
        "",
        "  /* Public pages: system fonts, 16 px body, and 16 px in every field so",
        "     iOS Safari does not zoom. */",
        '  :root[data-surface="public"] {',
        "    font-family: var(--family-public);",
        "  }",
        '  :root[data-surface="public"] body,',
        '  :root[data-surface="public"] :is(input, select, textarea, button) {',
        "    font-size: var(--type-base-size);",
        "    line-height: var(--type-base-line);",
        "  }",
        "",
        "  /* Focus: an outline, never a box-shadow alone (forced-colors mode drops",
        "     box-shadow). It appears at once, with no transition. */",
        "  :focus-visible {",
        "    outline: var(--focus-width) solid var(--focus-ring);",
        "    outline-offset: var(--focus-offset);",
        "  }",
        "}",
        "",
    ]
    return "\n".join(doc)


# -- main ----------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--light", default=os.path.join(HERE, "tokens.json"))
    ap.add_argument("--dark", default=os.path.join(HERE, "tokens.dark.json"))
    ap.add_argument("--out", default=HERE, help="folder for tokens.css and tailwind.css")
    ap.add_argument("--check", action="store_true", help="exit 1 if the CSS files are out of date")
    a = ap.parse_args(argv)
    try:
        light, dark = load(a.light), load(a.dark)
        check(light, dark)
    except TokenError as exc:
        print("build_tokens: %s" % exc, file=sys.stderr)
        return 2
    outputs = {
        "tokens.css": tokens_css(light, dark),
        "tailwind.css": tailwind_css(light),
    }
    stale = []
    for name, text in outputs.items():
        path = os.path.join(a.out, name)
        try:
            with open(path, encoding="utf-8") as fh:
                current = fh.read()
        except OSError:
            current = None
        if current == text:
            continue
        if a.check:
            stale.append(name)
            continue
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print("wrote %s" % path)
    if stale:
        print("build_tokens: out of date: %s. Run build_tokens.py." % ", ".join(stale), file=sys.stderr)
        return 1
    print("%d colour roles, %d pairs per theme" % (len(light["color"]), len(light["pairs"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
