// tw-merge.ts
// Generated by build_tokens.py from tokens.json (light) and tokens.dark.json (dark).
// Do not edit by hand. Change the JSON, run contrast.py on both files, then run
// python3 replica/design/build_tokens.py.
//
// accent, accent-hover, accent-subtle, focus-ring and chart-* are placeholders
// until /replica-brand sets our palette. The accent family is pure grey for now,
// so no hue from the original product is carried over.
//
// Fonts: Inter and Noto (SIL OFL 1.1). Icons: lucide-react (ISC; Feather-derived
// icons MIT, Cole Bemis). Licence texts ship in THIRD_PARTY_LICENSES with the
// vendored files.
//
// tailwind-merge only knows Tailwind's default names. Without this config it
// drops text-table when a later class is text-muted (it reads both as colours),
// and it keeps both h-control-sm and h-control-md. cn() in the app imports
// twMerge from this file:
//   export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));

import { extendTailwindMerge } from "tailwind-merge";

export const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      color: ["bg", "surface", "surface-subtle", "surface-raised", "surface-sunken", "surface-hover", "border", "strong", "input", "fg", "muted", "accent", "accent-hover", "accent-subtle", "on-accent", "focus-ring", "danger", "danger-hover", "danger-subtle", "on-danger", "success", "success-subtle", "on-success", "warning", "warning-subtle", "on-warning", "info", "info-subtle", "on-info", "inverse", "on-inverse", "overlay", "chart-surface", "chart-1", "chart-2", "chart-3", "chart-4", "chart-5", "chart-6", "chart-7", "chart-8", "chart-ordinal-1", "chart-ordinal-2", "chart-ordinal-3", "chart-ordinal-4", "chart-ordinal-5", "chart-ordinal-6"],
      text: ["xs", "table", "sm", "base", "md", "lg", "xl", "display"],
      leading: ["tight", "normal", "prose"],
      font: ["sans", "public", "mono"],
      "font-weight": ["normal", "medium", "semibold", "bold"],
      spacing: ["sidebar", "sidebar-collapsed", "header", "pagebar", "gutter", "gutter-sm", "section-gap", "subnav", "kv-label", "control-xs", "control-sm", "control-md", "control-lg", "row-compact", "row", "row-header", "table-footer", "menu-item", "chip", "kv-row", "checkbox", "hit", "hit-public", "avatar-sm", "avatar-md", "avatar-lg", "icon-sm", "icon-md", "icon-lg"],
      container: ["content", "form", "public", "dialog-sm", "dialog-md", "dialog-lg", "drawer-sm", "drawer-md", "drawer-lg"],
      radius: ["none", "xs", "sm", "md", "lg", "xl", "pill"],
      shadow: ["card", "bar", "pop", "modal"],
      ease: ["standard", "exit"],
      animate: ["fade-in", "fade-out", "rise-in", "pop-in", "slide-in-right", "slide-out-right", "slide-in-left", "slide-out-left", "indeterminate"],
    },
    classGroups: {
      duration: [{ duration: ["fast", "base", "slow"] }],
      "focus-inset": ["focus-inset"],
    },
  },
});
