// AUTO-GENERATED by scripts/gen-shared-enums.cjs from apps/api/prisma/schema.prisma — do not edit.

export const DashboardKind = {
  ADMIN: 'ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  ADMISSIONS: 'ADMISSIONS',
  ACCOUNTS: 'ACCOUNTS',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  FRONT_DESK: 'FRONT_DESK',
} as const;
export type DashboardKind = (typeof DashboardKind)[keyof typeof DashboardKind];
export const DashboardKindValues = Object.values(DashboardKind) as DashboardKind[];

export const DataScope = {
  ALL: 'ALL',
  OWN_CLASSES: 'OWN_CLASSES',
  OWN_CHILDREN: 'OWN_CHILDREN',
} as const;
export type DataScope = (typeof DataScope)[keyof typeof DataScope];
export const DataScopeValues = Object.values(DataScope) as DataScope[];

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  LOCKED: 'LOCKED',
} as const;
export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];
export const UserStatusValues = Object.values(UserStatus) as UserStatus[];

export const JobStatus = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];
export const JobStatusValues = Object.values(JobStatus) as JobStatus[];

export const AcademicYearStatus = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
} as const;
export type AcademicYearStatus = (typeof AcademicYearStatus)[keyof typeof AcademicYearStatus];
export const AcademicYearStatusValues = Object.values(AcademicYearStatus) as AcademicYearStatus[];

export const GradeStage = {
  PRE_PRIMARY: 'PRE_PRIMARY',
  PRIMARY: 'PRIMARY',
  MIDDLE: 'MIDDLE',
  SECONDARY: 'SECONDARY',
  SENIOR_SECONDARY: 'SENIOR_SECONDARY',
} as const;
export type GradeStage = (typeof GradeStage)[keyof typeof GradeStage];
export const GradeStageValues = Object.values(GradeStage) as GradeStage[];

export const SubjectType = {
  CORE: 'CORE',
  ELECTIVE: 'ELECTIVE',
  LANGUAGE: 'LANGUAGE',
  CO_SCHOLASTIC: 'CO_SCHOLASTIC',
} as const;
export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];
export const SubjectTypeValues = Object.values(SubjectType) as SubjectType[];

export const Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
export type Gender = (typeof Gender)[keyof typeof Gender];
export const GenderValues = Object.values(Gender) as Gender[];

export const StudentStatus = {
  ACTIVE: 'ACTIVE',
  WITHDRAWN: 'WITHDRAWN',
  GRADUATED: 'GRADUATED',
  TRANSFERRED: 'TRANSFERRED',
  INACTIVE: 'INACTIVE',
} as const;
export type StudentStatus = (typeof StudentStatus)[keyof typeof StudentStatus];
export const StudentStatusValues = Object.values(StudentStatus) as StudentStatus[];

export const EnrollmentStatus = {
  ACTIVE: 'ACTIVE',
  PROMOTED: 'PROMOTED',
  DETAINED: 'DETAINED',
  WITHDRAWN: 'WITHDRAWN',
  GRADUATED: 'GRADUATED',
} as const;
export type EnrollmentStatus = (typeof EnrollmentStatus)[keyof typeof EnrollmentStatus];
export const EnrollmentStatusValues = Object.values(EnrollmentStatus) as EnrollmentStatus[];

export const GuardianRelation = {
  FATHER: 'FATHER',
  MOTHER: 'MOTHER',
  GUARDIAN: 'GUARDIAN',
  GRANDPARENT: 'GRANDPARENT',
  OTHER: 'OTHER',
} as const;
export type GuardianRelation = (typeof GuardianRelation)[keyof typeof GuardianRelation];
export const GuardianRelationValues = Object.values(GuardianRelation) as GuardianRelation[];

export const DocumentType = {
  BIRTH_CERTIFICATE: 'BIRTH_CERTIFICATE',
  REPORT_CARD: 'REPORT_CARD',
  TRANSFER_CERTIFICATE: 'TRANSFER_CERTIFICATE',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  PHOTO: 'PHOTO',
  AADHAAR: 'AADHAAR',
  MEDICAL: 'MEDICAL',
  OTHER: 'OTHER',
} as const;
export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];
export const DocumentTypeValues = Object.values(DocumentType) as DocumentType[];

export const CustomFieldEntity = {
  STUDENT: 'STUDENT',
  STAFF: 'STAFF',
} as const;
export type CustomFieldEntity = (typeof CustomFieldEntity)[keyof typeof CustomFieldEntity];
export const CustomFieldEntityValues = Object.values(CustomFieldEntity) as CustomFieldEntity[];

export const CustomFieldType = {
  TEXT: 'TEXT',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  SELECT: 'SELECT',
  BOOLEAN: 'BOOLEAN',
} as const;
export type CustomFieldType = (typeof CustomFieldType)[keyof typeof CustomFieldType];
export const CustomFieldTypeValues = Object.values(CustomFieldType) as CustomFieldType[];

export const EnquirySource = {
  WALK_IN: 'WALK_IN',
  PHONE: 'PHONE',
  WEBSITE: 'WEBSITE',
  WHATSAPP: 'WHATSAPP',
  REFERRAL: 'REFERRAL',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  OTHER: 'OTHER',
} as const;
export type EnquirySource = (typeof EnquirySource)[keyof typeof EnquirySource];
export const EnquirySourceValues = Object.values(EnquirySource) as EnquirySource[];

export const EnquiryStage = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  VISIT_SCHEDULED: 'VISIT_SCHEDULED',
  APPLIED: 'APPLIED',
  OFFERED: 'OFFERED',
  ENROLLED: 'ENROLLED',
  WITHDRAWN: 'WITHDRAWN',
} as const;
export type EnquiryStage = (typeof EnquiryStage)[keyof typeof EnquiryStage];
export const EnquiryStageValues = Object.values(EnquiryStage) as EnquiryStage[];

export const ActivityType = {
  NOTE: 'NOTE',
  CALL: 'CALL',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP',
  VISIT: 'VISIT',
  STAGE_CHANGE: 'STAGE_CHANGE',
  SYSTEM: 'SYSTEM',
} as const;
export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType];
export const ActivityTypeValues = Object.values(ActivityType) as ActivityType[];

export const TaskStatus = {
  OPEN: 'OPEN',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
} as const;
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];
export const TaskStatusValues = Object.values(TaskStatus) as TaskStatus[];

export const ApplicationStatus = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ACCEPTED: 'ACCEPTED',
  WAITLISTED: 'WAITLISTED',
  REJECTED: 'REJECTED',
  ENROLLED: 'ENROLLED',
  WITHDRAWN: 'WITHDRAWN',
} as const;
export type ApplicationStatus = (typeof ApplicationStatus)[keyof typeof ApplicationStatus];
export const ApplicationStatusValues = Object.values(ApplicationStatus) as ApplicationStatus[];

export const PromotionStatus = {
  APPLIED: 'APPLIED',
  UNDONE: 'UNDONE',
} as const;
export type PromotionStatus = (typeof PromotionStatus)[keyof typeof PromotionStatus];
export const PromotionStatusValues = Object.values(PromotionStatus) as PromotionStatus[];

export const PromotionAction = {
  PROMOTED: 'PROMOTED',
  GRADUATED: 'GRADUATED',
  DETAINED: 'DETAINED',
  HELD_FOR_DUES: 'HELD_FOR_DUES',
} as const;
export type PromotionAction = (typeof PromotionAction)[keyof typeof PromotionAction];
export const PromotionActionValues = Object.values(PromotionAction) as PromotionAction[];

export const FeeCategory = {
  ADMISSION: 'ADMISSION',
  TUITION: 'TUITION',
  REGISTRATION: 'REGISTRATION',
  TRANSPORT: 'TRANSPORT',
  MEAL: 'MEAL',
  UNIFORM: 'UNIFORM',
  BOOKS: 'BOOKS',
  EXAM: 'EXAM',
  ACTIVITY: 'ACTIVITY',
  LATE_FEE: 'LATE_FEE',
  OTHER: 'OTHER',
} as const;
export type FeeCategory = (typeof FeeCategory)[keyof typeof FeeCategory];
export const FeeCategoryValues = Object.values(FeeCategory) as FeeCategory[];

export const FeeStructureStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
} as const;
export type FeeStructureStatus = (typeof FeeStructureStatus)[keyof typeof FeeStructureStatus];
export const FeeStructureStatusValues = Object.values(FeeStructureStatus) as FeeStructureStatus[];

export const FeeFrequency = {
  ONE_TIME: 'ONE_TIME',
  ANNUAL: 'ANNUAL',
  PER_TERM: 'PER_TERM',
} as const;
export type FeeFrequency = (typeof FeeFrequency)[keyof typeof FeeFrequency];
export const FeeFrequencyValues = Object.values(FeeFrequency) as FeeFrequency[];

export const FeeApplicability = {
  ALL: 'ALL',
  NEW_ADMISSION: 'NEW_ADMISSION',
  EXISTING: 'EXISTING',
} as const;
export type FeeApplicability = (typeof FeeApplicability)[keyof typeof FeeApplicability];
export const FeeApplicabilityValues = Object.values(FeeApplicability) as FeeApplicability[];

export const LateFeeMode = {
  FIXED: 'FIXED',
  PERCENT: 'PERCENT',
} as const;
export type LateFeeMode = (typeof LateFeeMode)[keyof typeof LateFeeMode];
export const LateFeeModeValues = Object.values(LateFeeMode) as LateFeeMode[];

export const LateFeeFrequency = {
  ONCE: 'ONCE',
  PER_DAY: 'PER_DAY',
  PER_WEEK: 'PER_WEEK',
  PER_MONTH: 'PER_MONTH',
} as const;
export type LateFeeFrequency = (typeof LateFeeFrequency)[keyof typeof LateFeeFrequency];
export const LateFeeFrequencyValues = Object.values(LateFeeFrequency) as LateFeeFrequency[];

export const DiscountType = {
  SIBLING: 'SIBLING',
  STAFF_CHILD: 'STAFF_CHILD',
  MERIT_SCHOLARSHIP: 'MERIT_SCHOLARSHIP',
  SPECIAL_CONCESSION: 'SPECIAL_CONCESSION',
  OTHER: 'OTHER',
} as const;
export type DiscountType = (typeof DiscountType)[keyof typeof DiscountType];
export const DiscountTypeValues = Object.values(DiscountType) as DiscountType[];

export const DiscountMode = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
} as const;
export type DiscountMode = (typeof DiscountMode)[keyof typeof DiscountMode];
export const DiscountModeValues = Object.values(DiscountMode) as DiscountMode[];

export const ApprovalStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVOKED: 'REVOKED',
} as const;
export type ApprovalStatus = (typeof ApprovalStatus)[keyof typeof ApprovalStatus];
export const ApprovalStatusValues = Object.values(ApprovalStatus) as ApprovalStatus[];

export const InvoiceType = {
  TERM: 'TERM',
  ADMISSION: 'ADMISSION',
  MANUAL: 'MANUAL',
  OPENING_BALANCE: 'OPENING_BALANCE',
  STORE: 'STORE',
} as const;
export type InvoiceType = (typeof InvoiceType)[keyof typeof InvoiceType];
export const InvoiceTypeValues = Object.values(InvoiceType) as InvoiceType[];

export const InvoiceStatus = {
  PENDING: 'PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED',
} as const;
export type InvoiceStatus = (typeof InvoiceStatus)[keyof typeof InvoiceStatus];
export const InvoiceStatusValues = Object.values(InvoiceStatus) as InvoiceStatus[];

export const AdjustmentType = {
  WAIVER: 'WAIVER',
  LATE_FEE_WAIVER: 'LATE_FEE_WAIVER',
  DISCOUNT: 'DISCOUNT',
  CORRECTION_INCREASE: 'CORRECTION_INCREASE',
  CORRECTION_DECREASE: 'CORRECTION_DECREASE',
} as const;
export type AdjustmentType = (typeof AdjustmentType)[keyof typeof AdjustmentType];
export const AdjustmentTypeValues = Object.values(AdjustmentType) as AdjustmentType[];

export const PaymentMode = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHEQUE: 'CHEQUE',
  UPI: 'UPI',
  CARD: 'CARD',
  NET_BANKING: 'NET_BANKING',
  WALLET: 'WALLET',
  OPENING_CREDIT: 'OPENING_CREDIT',
} as const;
export type PaymentMode = (typeof PaymentMode)[keyof typeof PaymentMode];
export const PaymentModeValues = Object.values(PaymentMode) as PaymentMode[];

export const PaymentStatus = {
  PENDING_CLEARANCE: 'PENDING_CLEARANCE',
  SUCCESS: 'SUCCESS',
  BOUNCED: 'BOUNCED',
  FAILED: 'FAILED',
  VOID: 'VOID',
} as const;
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];
export const PaymentStatusValues = Object.values(PaymentStatus) as PaymentStatus[];

export const PaymentChannel = {
  COUNTER: 'COUNTER',
  ONLINE: 'ONLINE',
  IMPORT: 'IMPORT',
} as const;
export type PaymentChannel = (typeof PaymentChannel)[keyof typeof PaymentChannel];
export const PaymentChannelValues = Object.values(PaymentChannel) as PaymentChannel[];

export const Gateway = {
  RAZORPAY: 'RAZORPAY',
  STRIPE: 'STRIPE',
  MOCK: 'MOCK',
} as const;
export type Gateway = (typeof Gateway)[keyof typeof Gateway];
export const GatewayValues = Object.values(Gateway) as Gateway[];

export const GatewayOrderStatus = {
  CREATED: 'CREATED',
  ATTEMPTED: 'ATTEMPTED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
} as const;
export type GatewayOrderStatus = (typeof GatewayOrderStatus)[keyof typeof GatewayOrderStatus];
export const GatewayOrderStatusValues = Object.values(GatewayOrderStatus) as GatewayOrderStatus[];

export const WebhookStatus = {
  RECEIVED: 'RECEIVED',
  PROCESSED: 'PROCESSED',
  IGNORED: 'IGNORED',
  FAILED: 'FAILED',
} as const;
export type WebhookStatus = (typeof WebhookStatus)[keyof typeof WebhookStatus];
export const WebhookStatusValues = Object.values(WebhookStatus) as WebhookStatus[];

export const RefundStatus = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
} as const;
export type RefundStatus = (typeof RefundStatus)[keyof typeof RefundStatus];
export const RefundStatusValues = Object.values(RefundStatus) as RefundStatus[];

export const RefundSource = {
  WALLET: 'WALLET',
  PAYMENT: 'PAYMENT',
} as const;
export type RefundSource = (typeof RefundSource)[keyof typeof RefundSource];
export const RefundSourceValues = Object.values(RefundSource) as RefundSource[];

export const RefundMethod = {
  ORIGINAL_GATEWAY: 'ORIGINAL_GATEWAY',
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHEQUE: 'CHEQUE',
} as const;
export type RefundMethod = (typeof RefundMethod)[keyof typeof RefundMethod];
export const RefundMethodValues = Object.values(RefundMethod) as RefundMethod[];

export const LedgerEntryType = {
  INVOICE: 'INVOICE',
  DISCOUNT: 'DISCOUNT',
  LATE_FEE: 'LATE_FEE',
  ADJUSTMENT: 'ADJUSTMENT',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  PAYMENT: 'PAYMENT',
  PAYMENT_REVERSAL: 'PAYMENT_REVERSAL',
  REFUND: 'REFUND',
  OPENING_BALANCE: 'OPENING_BALANCE',
} as const;
export type LedgerEntryType = (typeof LedgerEntryType)[keyof typeof LedgerEntryType];
export const LedgerEntryTypeValues = Object.values(LedgerEntryType) as LedgerEntryType[];

export const CommitmentStatus = {
  PENDING: 'PENDING',
  KEPT: 'KEPT',
  PARTIALLY_KEPT: 'PARTIALLY_KEPT',
  BROKEN: 'BROKEN',
  CANCELLED: 'CANCELLED',
} as const;
export type CommitmentStatus = (typeof CommitmentStatus)[keyof typeof CommitmentStatus];
export const CommitmentStatusValues = Object.values(CommitmentStatus) as CommitmentStatus[];

export const NotificationChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP',
  IN_APP: 'IN_APP',
} as const;
export type NotificationChannel = (typeof NotificationChannel)[keyof typeof NotificationChannel];
export const NotificationChannelValues = Object.values(NotificationChannel) as NotificationChannel[];

export const FeePolicyType = {
  BLOCK_REPORT_CARD: 'BLOCK_REPORT_CARD',
  BLOCK_ADMIT_CARD: 'BLOCK_ADMIT_CARD',
  RESTRICT_PARENT_PORTAL: 'RESTRICT_PARENT_PORTAL',
} as const;
export type FeePolicyType = (typeof FeePolicyType)[keyof typeof FeePolicyType];
export const FeePolicyTypeValues = Object.values(FeePolicyType) as FeePolicyType[];

export const ReconciliationItemStatus = {
  MATCHED: 'MATCHED',
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',
  MISSING_IN_SYSTEM: 'MISSING_IN_SYSTEM',
  MISSING_IN_GATEWAY: 'MISSING_IN_GATEWAY',
} as const;
export type ReconciliationItemStatus = (typeof ReconciliationItemStatus)[keyof typeof ReconciliationItemStatus];
export const ReconciliationItemStatusValues = Object.values(ReconciliationItemStatus) as ReconciliationItemStatus[];

export const NotificationStatus = {
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  SIMULATED: 'SIMULATED',
  SKIPPED: 'SKIPPED',
} as const;
export type NotificationStatus = (typeof NotificationStatus)[keyof typeof NotificationStatus];
export const NotificationStatusValues = Object.values(NotificationStatus) as NotificationStatus[];

export const BroadcastCategory = {
  GENERAL: 'GENERAL',
  FEES: 'FEES',
  ATTENDANCE: 'ATTENDANCE',
  HOMEWORK: 'HOMEWORK',
  EVENT: 'EVENT',
  EMERGENCY: 'EMERGENCY',
} as const;
export type BroadcastCategory = (typeof BroadcastCategory)[keyof typeof BroadcastCategory];
export const BroadcastCategoryValues = Object.values(BroadcastCategory) as BroadcastCategory[];

export const BroadcastStatus = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  SENDING: 'SENDING',
  SENT: 'SENT',
} as const;
export type BroadcastStatus = (typeof BroadcastStatus)[keyof typeof BroadcastStatus];
export const BroadcastStatusValues = Object.values(BroadcastStatus) as BroadcastStatus[];

export const AttendanceStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  HALF_DAY: 'HALF_DAY',
  LEAVE: 'LEAVE',
} as const;
export type AttendanceStatus = (typeof AttendanceStatus)[keyof typeof AttendanceStatus];
export const AttendanceStatusValues = Object.values(AttendanceStatus) as AttendanceStatus[];

export const ExamType = {
  PERIODIC_TEST: 'PERIODIC_TEST',
  NOTEBOOK: 'NOTEBOOK',
  SUBJECT_ENRICHMENT: 'SUBJECT_ENRICHMENT',
  HALF_YEARLY: 'HALF_YEARLY',
  ANNUAL: 'ANNUAL',
  UNIT_TEST: 'UNIT_TEST',
} as const;
export type ExamType = (typeof ExamType)[keyof typeof ExamType];
export const ExamTypeValues = Object.values(ExamType) as ExamType[];

export const ExamStatus = {
  SCHEDULED: 'SCHEDULED',
  MARKS_ENTRY: 'MARKS_ENTRY',
  COMPLETED: 'COMPLETED',
  PUBLISHED: 'PUBLISHED',
} as const;
export type ExamStatus = (typeof ExamStatus)[keyof typeof ExamStatus];
export const ExamStatusValues = Object.values(ExamStatus) as ExamStatus[];

export const StaffType = {
  TEACHING: 'TEACHING',
  NON_TEACHING: 'NON_TEACHING',
  ADMINISTRATIVE: 'ADMINISTRATIVE',
  SUPPORT: 'SUPPORT',
} as const;
export type StaffType = (typeof StaffType)[keyof typeof StaffType];
export const StaffTypeValues = Object.values(StaffType) as StaffType[];

export const StaffStatus = {
  ACTIVE: 'ACTIVE',
  ON_LEAVE: 'ON_LEAVE',
  RESIGNED: 'RESIGNED',
  TERMINATED: 'TERMINATED',
} as const;
export type StaffStatus = (typeof StaffStatus)[keyof typeof StaffStatus];
export const StaffStatusValues = Object.values(StaffStatus) as StaffStatus[];

export const PayrollStatus = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
  PAID: 'PAID',
} as const;
export type PayrollStatus = (typeof PayrollStatus)[keyof typeof PayrollStatus];
export const PayrollStatusValues = Object.values(PayrollStatus) as PayrollStatus[];

export const AccountType = {
  ASSET: 'ASSET',
  LIABILITY: 'LIABILITY',
  EQUITY: 'EQUITY',
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
export type AccountType = (typeof AccountType)[keyof typeof AccountType];
export const AccountTypeValues = Object.values(AccountType) as AccountType[];

export const VoucherType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
export type VoucherType = (typeof VoucherType)[keyof typeof VoucherType];
export const VoucherTypeValues = Object.values(VoucherType) as VoucherType[];

export const VoucherStatus = {
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  CANCELLED: 'CANCELLED',
} as const;
export type VoucherStatus = (typeof VoucherStatus)[keyof typeof VoucherStatus];
export const VoucherStatusValues = Object.values(VoucherStatus) as VoucherStatus[];

export const StoreCategory = {
  UNIFORM: 'UNIFORM',
  BOOKS: 'BOOKS',
  STATIONERY: 'STATIONERY',
  OTHER: 'OTHER',
} as const;
export type StoreCategory = (typeof StoreCategory)[keyof typeof StoreCategory];
export const StoreCategoryValues = Object.values(StoreCategory) as StoreCategory[];

export const SaleStatus = {
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
export type SaleStatus = (typeof SaleStatus)[keyof typeof SaleStatus];
export const SaleStatusValues = Object.values(SaleStatus) as SaleStatus[];

export const CertificateType = {
  BONAFIDE: 'BONAFIDE',
  CHARACTER: 'CHARACTER',
  TRANSFER: 'TRANSFER',
  LEAVING: 'LEAVING',
  MERIT: 'MERIT',
  CUSTOM: 'CUSTOM',
} as const;
export type CertificateType = (typeof CertificateType)[keyof typeof CertificateType];
export const CertificateTypeValues = Object.values(CertificateType) as CertificateType[];

export const EventCategory = {
  HOLIDAY: 'HOLIDAY',
  EXAM: 'EXAM',
  EVENT: 'EVENT',
  MEETING: 'MEETING',
  PTM: 'PTM',
  SPORTS: 'SPORTS',
  CULTURAL: 'CULTURAL',
} as const;
export type EventCategory = (typeof EventCategory)[keyof typeof EventCategory];
export const EventCategoryValues = Object.values(EventCategory) as EventCategory[];

